version: 2
jobs:
  build:
    working_directory: ~/kaizenplatform/kaizen-ui-colors
    docker:
    - image: circleci/ruby:2-node
    steps:
    - checkout
    - run:
        working_directory: ~/kaizenplatform/kaizen-ui-colors
        command: echo 'Host *' >> $HOME/.ssh/config
    - run:
        working_directory: ~/kaizenplatform/kaizen-ui-colors
        command: echo 'ForwardAgent yes' >> $HOME/.ssh/config
    - run:
        working_directory: ~/kaizenplatform/kaizen-ui-colors
        command: git config --global user.name 'Circle CI'
    - run:
        working_directory: ~/kaizenplatform/kaizen-ui-colors
        command: git config --global user.email 'dev-team@kaizenplatform.com'
    # Dependencies
    - run: gem install --no-rdoc --no-ri sass
    # build
    - run: ./scripts/convert.sh
    # Test
    - run: exit 0
    - store_artifacts:
        path: preview
    # Deployment
    - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ ^master$ ]]; then
              ./scripts/deploy.sh
            fi
